[phases.setup]
nixPkgs = ["nodejs", "python3", "make", "gcc", "g++"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx http-server dist/ng-gradient-able -p $PORT"
