[build]
nixpacksVersion = 1
builder = 'nixpacks'

[variables]
NODE_OPTIONS = '--openssl-legacy-provider'

[phases.build]
cmds = ['npm install', 'npm run build']

[start]
cmd = 'npx http-server dist/ng-gradient-able -p $PORT'